# Pipeline By Grenston George
# Used to build, test, and deploy PartsUnlimitted ASP.net website
# Multistage used to deploy to test and production environment in localmachine, IIS Server

trigger:
- master

stages:
 - stage: Build
   jobs:
   - job: Build
     pool:
       vmImage: 'VS2017-Win2016'

     variables:
       - group: build-vars 

     steps:
     - task: NuGetToolInstaller@0

     - task: NuGetCommand@2
       inputs:
         restoreSolution: '$(solution)'

     - task: VSBuild@1
       inputs:
         solution: '$(solution)'
         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
         platform: '$(buildPlatform)'
         configuration: '$(buildConfiguration)'

     - task: VSTest@2
       inputs:
         platform: '$(buildPlatform)'
         configuration: '$(buildConfiguration)'

     - task: CopyFiles@2
       displayName: 'Copy Files'
       inputs:
         SourceFolder: '$(build.sourcesdirectory)'
         Contents: '**/*.json'
         TargetFolder: '$(build.artifactstagingdirectory)'

     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)'
 
 - stage: DeployToTest
   jobs:
   - job: DeployToTest
     pool:
       name: 'GrenP'

     steps:
       - task: DownloadPipelineArtifact@2
         inputs:
           source: 'current'
           path: '$(Pipeline.Workspace)'

       - task: IISWebAppManagementOnMachineGroup@0
         displayName: 'Manage IISWebsite'
         inputs:
           WebsiteName: pultest
           AddBinding: true
           Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8978","hostname":"","sslThumbprint":"","sniFlag":false}]}'
           CreateOrUpdateAppPoolForWebsite: true
           AppPoolNameForWebsite: pul
           AppPoolIdentityForWebsite: NetworkService
     
       - task: IISWebAppDeploymentOnMachineGroup@0
         displayName: 'Deploy IIS Website/App: '
         inputs:
           WebSiteName: 'pultest'
           Package: '$(Pipeline.Workspace)\**\*.zip'

 - stage: DeployToProduction  
   jobs:
   - deployment: DeployToProduction
     pool:
       name: 'GrenP'
       
     environment: 'production'
     strategy:
      runOnce:
        deploy:
         steps:
         - task: DownloadPipelineArtifact@2
           inputs:
             source: 'current'
             path: '$(Pipeline.Workspace)'

         - task: IISWebAppManagementOnMachineGroup@0
           displayName: 'Manage IISWebsite'
           inputs:
             WebsiteName: pul
             AddBinding: true
             Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"6978","hostname":"","sslThumbprint":"","sniFlag":false}]}'
             CreateOrUpdateAppPoolForWebsite: true
             AppPoolNameForWebsite: pul
             AppPoolIdentityForWebsite: NetworkService
     
         - task: IISWebAppDeploymentOnMachineGroup@0
           displayName: 'Deploy IIS Website/App: '
           inputs:
             WebSiteName: 'pul'
             Package: '$(Pipeline.Workspace)\**\*.zip'
         
    