name: ASPBuild

on:[push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0 
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
       version: 2.2.104
   - name: Build with .NET
     run: dotnet build --configuration release 


