name: ASPBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.100' 
     
      - name: Install Package
        run: |
          cd .\PartsUnlimited-aspnet45
          dotnet add PartsUnlimited Install-Package Microsoft.DependencyValidation.Analyzers --version 0.10.0
          cd ..
      - name: BuildApp  
        run: |
         Get-Content -Path .\PartsUnlimited-aspnet45\PartsUnlimited.sln
         dotnet restore .\PartsUnlimited-aspnet45\PartsUnlimited.sln
         dotnet build .\PartsUnlimited-aspnet45\PartsUnlimited.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$env:GITHUB_WORKSPACE"

