name: ASPBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.100' 
      - name: BuildApp  
        run: |
         dotnet restore **\*.sln
         dotnet build **\*.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$env:GITHUB_WORKSPACE"

