name: ASPBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0 
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
       version: 2.2.104
    - name: Build with .NET
      run: dotnet build **/*.sln --configuration release 


