# This is a basic workflow to help you get started with Actions

name: PUBLISH_PACKAGES

on:
  push:
    branches: [ test ]
    paths: 
      - MyPackages/**
jobs:
  PUBLISH_PACKAGES:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: NuGet Pack
      run: |
        nuget pack MyPackages\SampleClassLib\SampleLib\SampleLib.csproj -OutFile ${{github.workspace}}\MyPackages
        nuget pack MyPackages\SamplePkg\SamplePkg.nuspec -OutFile ${{github.workspace}}\MyPackages

    - name: Publish Packages
      run: |
        nuget push MyPackages\*.nupkg -Source -ApiKey gh -SkipDuplicate
