# This is a basic workflow to help you get started with Actions

name: PUBLISH_PACKAGES

on:
  push:
    branches: [ master ]
 
jobs:
  PUBLISH_PACKAGES:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: NuGet Pack
      run: |
        nuget pack MyPackages\SampleClassLib\SampleLib\SampleLib.csproj -OutputDirectory ${{github.workspace}}\MyPackages
        nuget pack MyPackages\SamplePkg\SamplePkg.nuspec -OutputDirectory ${{github.workspace}}\MyPackages
    - name: Publish Packages
      run: |
        nuget sources add -Name ghpackages -Source https://nuget.pkg.github.com/OWNER/index.json -username Grenston -password ${{secrets.GITHUB_TOKEN}}
        nuget push MyPackages\*.nupkg -Source ghpackages -ApiKey gh -SkipDuplicate
